### ISSUE TITLE
Any guide information for building this project

### ISSUE THREAD

**Issue by yanggf8** [johnperry/MIRC2#2]
Dear All,
   I am quiet new to MIRC and TPS. I know TPS is a plugin for CTP. Just don't know how to build TPS with CTP. I come across the wiki will try to setup same directory structure of them

**Comment by johnperry** [comment]
I'm not sure what TPS is.

If you mean TFS (Teaching File System), you don't need to build it; you can just use the TFS-installer.jar program from the RSNA MIRC site:

    http://mirc.rsna.org/download/TFS-installer.jar

The installer installs CTP with the MIRC plugin. Together, that creates TFS.

Documentation is on the RSNA MIRC Wiki (http://mircwiki.rsna.org). The top level article is:

    http://mircwiki.rsna.org/index.php?title=MIRC_TFS

The best place to post questions is on the Google group:

    https://groups.google.com/forum/#!forum/rsnas-ctpmirc-user-group

JP



From: yanggf8 
Sent: Tuesday, August 13, 2019 1:40 AM
To: johnperry/MIRC2 
Cc: Subscribed 
Subject: [johnperry/MIRC2] Any guide information for building this project (#2)

Dear All,
I am quiet new to MIRC and TPS. I know TPS is a plugin for CTP. Just don't know how to build TPS with CTP. Should I just clone TPS at the same directory of CTP and build them together? Do we need to change CTP's build.xml in order to build successfully with TPS.

**Comment by yanggf8** [comment]
Cool, Thank you so much. Following your instructions I am able to build up the project. :) Thanks
